---
- name: Check if pnpm is already installed
  stat:
    path: "{{ user_home }}/.local/share/pnpm/pnpm"
  register: pnpm_bin

- name: Install pnpm
  shell: curl -fsSL https://get.pnpm.io/install.sh | sh -
  when: not pnpm_bin.stat.exists
  args:
    executable: /bin/bash
